/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.guerra.simplepuntodeventa.vista.inventario;

import com.guerra.simplepuntodeventa.recursos.utilerias.TablaUtil;

/**
 *
 * @author Jaasiel
 */
public class PanListInventario extends javax.swing.JPanel {

    /**
     * Creates new form PanListArticulos
     */
    public PanListInventario() {
        initComponents();

        TablaUtil.ocultarCol(tblInventario, 8);
        
        TablaUtil.anchoMinimoColumna(tblInventario, 1, 275);
        TablaUtil.anchoMinimoColumna(tblInventario, 0, 50);
//        TablaUtil.setCellRender(tblInventario, 0, RenderCeldas.getRenderCodigo());
//        TablaUtil.setCellRender(tblInventario, 2, RenderCeldas.getRenderCantidad());
//        TablaUtil.setCellRender(tblInventario, 4, RenderCeldas.getRenderMoneda());
//        TablaUtil.setCellRender(tblInventario, 5, RenderCeldas.getRenderMoneda());
//        TablaUtil.setCellRender(tblInventario, 6, RenderCeldas.getRenderPorcentaje());
//        TablaUtil.setCellRender(tblInventario, 7, RenderCeldas.getRenderMoneda());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblInventario = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtBuscarArticulo = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtInventarioTotal = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        txtCostoTotal = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        txtGananciaTotal = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText("INVENTARIO");

        tblInventario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "CÓDIGO(1)", "ARTÍCULO (NOMBRE)", "CANTIDAD", "MIN. CANTIDAD", "P. COMPRA", "P. VENTA", "% GANANCIA", "GANANCIA UNIT.", "min_cantidad_aux"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblInventario.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(tblInventario);

        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        jLabel3.setText("Buscar artículo");
        jPanel1.add(jLabel3);

        txtBuscarArticulo.setPreferredSize(new java.awt.Dimension(175, 24));
        jPanel1.add(txtBuscarArticulo);

        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        jLabel2.setText("INVENTARIO TOTAL:");
        jPanel2.add(jLabel2);

        txtInventarioTotal.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        txtInventarioTotal.setForeground(new java.awt.Color(153, 0, 0));
        txtInventarioTotal.setText("0");
        jPanel2.add(txtInventarioTotal);

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator1.setPreferredSize(new java.awt.Dimension(20, 20));
        jPanel2.add(jSeparator1);

        jLabel5.setText("COSTO TOTAL:");
        jPanel2.add(jLabel5);

        txtCostoTotal.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        txtCostoTotal.setForeground(new java.awt.Color(153, 0, 0));
        txtCostoTotal.setText("0");
        jPanel2.add(txtCostoTotal);

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator2.setPreferredSize(new java.awt.Dimension(20, 20));
        jPanel2.add(jSeparator2);

        jLabel7.setText("GANANCIA TOTAL:");
        jPanel2.add(jLabel7);

        txtGananciaTotal.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        txtGananciaTotal.setForeground(new java.awt.Color(153, 0, 0));
        txtGananciaTotal.setText("0");
        jPanel2.add(txtGananciaTotal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 635, Short.MAX_VALUE))
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 408, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    public javax.swing.JTable tblInventario;
    public javax.swing.JTextField txtBuscarArticulo;
    public javax.swing.JLabel txtCostoTotal;
    public javax.swing.JLabel txtGananciaTotal;
    public javax.swing.JLabel txtInventarioTotal;
    // End of variables declaration//GEN-END:variables
}
