/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.guerra.simplepuntodeventa.vista;

import javax.swing.JFrame;

/**
 *
 * @author Jaasiel Guerra
 */
public class FrmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public FrmPrincipal() {
        initComponents();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlCabecera = new javax.swing.JPanel();
        pnlBarraSuperior = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel34 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        btnCerrarSistema = new javax.swing.JLabel();
        pnlMenu = new javax.swing.JPanel();
        btnVentas = new javax.swing.JButton();
        btnArticulos = new javax.swing.JButton();
        btnInventario = new javax.swing.JButton();
        btnCompras = new javax.swing.JButton();
        btnClientes = new javax.swing.JButton();
        btnReportes = new javax.swing.JButton();
        btnConfiguracion = new javax.swing.JButton();
        pnlCentral = new javax.swing.JPanel();
        panPrincipal = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        setMinimumSize(new java.awt.Dimension(1024, 768));

        pnlCabecera.setLayout(new java.awt.BorderLayout());

        pnlBarraSuperior.setPreferredSize(new java.awt.Dimension(1000, 60));
        pnlBarraSuperior.setLayout(new javax.swing.BoxLayout(pnlBarraSuperior, javax.swing.BoxLayout.X_AXIS));

        jPanel6.setBackground(new java.awt.Color(0, 0, 0));
        jPanel6.setMaximumSize(new java.awt.Dimension(200, 32767));
        jPanel6.setMinimumSize(new java.awt.Dimension(0, 50));
        jPanel6.setPreferredSize(new java.awt.Dimension(400, 50));
        jPanel6.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/punto-de-venta.png"))); // NOI18N
        jLabel1.setText("<html><span style=\"font-size: 17px;\"\\>Mi Empresa</span><br/>Simple punto de Venta</html>");
        jPanel6.add(jLabel1, java.awt.BorderLayout.CENTER);

        pnlBarraSuperior.add(jPanel6);

        jPanel7.setBackground(new java.awt.Color(0, 0, 0));
        jPanel7.setMinimumSize(new java.awt.Dimension(0, 50));
        jPanel7.setPreferredSize(new java.awt.Dimension(500, 50));
        jPanel7.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 15, 3));

        jLabel34.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-calendar-40.png"))); // NOI18N
        jLabel34.setText("<html>12/10/2020<br>13:54:36");
        jLabel34.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel7.add(jLabel34);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nombre usuario", "Cerrar sesion" }));
        jComboBox1.setToolTipText("");
        jPanel7.add(jComboBox1);

        btnCerrarSistema.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-cerrar-ventana-32.png"))); // NOI18N
        btnCerrarSistema.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel7.add(btnCerrarSistema);

        pnlBarraSuperior.add(jPanel7);

        pnlCabecera.add(pnlBarraSuperior, java.awt.BorderLayout.PAGE_START);

        pnlMenu.setBackground(new java.awt.Color(255, 255, 255));
        pnlMenu.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        btnVentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-pos-terminal-40.png"))); // NOI18N
        btnVentas.setText("Ventas");
        btnVentas.setFocusPainted(false);
        btnVentas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnVentas.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        pnlMenu.add(btnVentas);

        btnArticulos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-subwoofer-40.png"))); // NOI18N
        btnArticulos.setText("Artículos");
        btnArticulos.setFocusPainted(false);
        btnArticulos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnArticulos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        pnlMenu.add(btnArticulos);

        btnInventario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-trolley-40.png"))); // NOI18N
        btnInventario.setText("Inventario");
        btnInventario.setFocusPainted(false);
        btnInventario.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnInventario.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        pnlMenu.add(btnInventario);

        btnCompras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-shopping-cart-40.png"))); // NOI18N
        btnCompras.setText("Compras");
        btnCompras.setFocusPainted(false);
        btnCompras.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCompras.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        pnlMenu.add(btnCompras);

        btnClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-user-group-40.png"))); // NOI18N
        btnClientes.setText("Clientes");
        btnClientes.setFocusPainted(false);
        btnClientes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnClientes.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        pnlMenu.add(btnClientes);

        btnReportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-combo-chart-40.png"))); // NOI18N
        btnReportes.setText("Reportes");
        btnReportes.setFocusPainted(false);
        btnReportes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnReportes.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        pnlMenu.add(btnReportes);

        btnConfiguracion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-gear-40.png"))); // NOI18N
        btnConfiguracion.setText("Configuración");
        btnConfiguracion.setFocusPainted(false);
        btnConfiguracion.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnConfiguracion.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        pnlMenu.add(btnConfiguracion);

        pnlCabecera.add(pnlMenu, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(pnlCabecera, java.awt.BorderLayout.PAGE_START);

        pnlCentral.setLayout(new java.awt.BorderLayout());
        pnlCentral.add(panPrincipal, java.awt.BorderLayout.CENTER);

        getContentPane().add(pnlCentral, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnArticulos;
    public javax.swing.JLabel btnCerrarSistema;
    public javax.swing.JButton btnClientes;
    public javax.swing.JButton btnCompras;
    public javax.swing.JButton btnConfiguracion;
    public javax.swing.JButton btnInventario;
    public javax.swing.JButton btnReportes;
    public javax.swing.JButton btnVentas;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    public javax.swing.JDesktopPane panPrincipal;
    public javax.swing.JPanel pnlBarraSuperior;
    private javax.swing.JPanel pnlCabecera;
    private javax.swing.JPanel pnlCentral;
    private javax.swing.JPanel pnlMenu;
    // End of variables declaration//GEN-END:variables
}
