/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.guerra.simplepuntodeventa.vista.reportes;

/**
 *
 * @author Jaasiel
 */
public class IfrmMenuReportes extends javax.swing.JInternalFrame {

    /**
     * Creates new form ifrmVentas
     */
    public IfrmMenuReportes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panCentral = new javax.swing.JPanel();
        btnReporteInventario = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        btnCatalogoArticulos = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("REPORTES");
        setMinimumSize(new java.awt.Dimension(960, 540));
        setPreferredSize(new java.awt.Dimension(960, 540));

        panCentral.setLayout(new java.awt.GridLayout(3, 3, 30, 30));

        btnReporteInventario.setBackground(new java.awt.Color(245, 127, 23));
        btnReporteInventario.setForeground(new java.awt.Color(255, 255, 255));
        btnReporteInventario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-warehouse-100.png"))); // NOI18N
        btnReporteInventario.setText("<html><b style=\"font-size: 14px;\">Inventario.</b> <p>Reporte de inventario de artículos activos.</p>");
        btnReporteInventario.setFocusPainted(false);
        panCentral.add(btnReporteInventario);

        jButton1.setBackground(new java.awt.Color(1, 87, 155));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-circled-user-100.png"))); // NOI18N
        jButton1.setText("<html><b style=\"font-size: 14px;\">Estado de cuenta.</b> <p>Reporte de estado de cuenta de un Cliente en específico.</p>");
        panCentral.add(jButton1);

        jButton2.setBackground(new java.awt.Color(0, 96, 100));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-sales-performance-100.png"))); // NOI18N
        jButton2.setText("<html><b style=\"font-size: 14px;\">Ventas.</b> <p>Reporte de ventas realizadas en un rango de fecha especificado.</p>");
        panCentral.add(jButton2);

        jButton3.setBackground(new java.awt.Color(74, 20, 140));
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-shopping-cart-100.png"))); // NOI18N
        jButton3.setText("<html><b style=\"font-size: 14px;\">Compras.</b> <p>Reporte de compras realizadas en un rango de fecha indicado.</p>");
        panCentral.add(jButton3);

        jButton4.setBackground(new java.awt.Color(130, 119, 23));
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-profile-100.png"))); // NOI18N
        jButton4.setText("<html><b style=\"font-size: 14px;\">Créditos pendientes.</b> <p>Reporte de Clientes que tienen créditos pendientes y su respectivo saldo.</p>");
        panCentral.add(jButton4);

        jButton5.setBackground(new java.awt.Color(183, 28, 28));
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-descending-sorting-100.png"))); // NOI18N
        jButton5.setText("<html><b style=\"font-size: 14px;\">Inventario bajo.</b> <p>Reporte de los artículos que están bajos en inventario.</p>");
        panCentral.add(jButton5);

        btnCatalogoArticulos.setBackground(new java.awt.Color(26, 35, 126));
        btnCatalogoArticulos.setForeground(new java.awt.Color(255, 255, 255));
        btnCatalogoArticulos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-show-property-100.png"))); // NOI18N
        btnCatalogoArticulos.setText("<html><b style=\"font-size: 14px;\">Catálogo de artículos.</b> <p>Reporte de catálogo de artículos registrados en el sistema.</p>");
        panCentral.add(btnCatalogoArticulos);

        jButton7.setBackground(new java.awt.Color(27, 94, 32));
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-total-sales-100.png"))); // NOI18N
        jButton7.setText("<html><b style=\"font-size: 14px;\">Ganancias.</b> <p>Reporte de las ganancias obtenidas de las ventas realizadas.</p>");
        panCentral.add(jButton7);

        jButton8.setBackground(new java.awt.Color(136, 14, 79));
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-pay-date-100.png"))); // NOI18N
        jButton8.setText("<html><b style=\"font-size: 14px;\">Movimientos.</b> <p>Reporte de movimientos del inventario.</p>");
        panCentral.add(jButton8);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panCentral, javax.swing.GroupLayout.PREFERRED_SIZE, 786, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panCentral, javax.swing.GroupLayout.DEFAULT_SIZE, 466, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnCatalogoArticulos;
    public javax.swing.JButton btnReporteInventario;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    public javax.swing.JPanel panCentral;
    // End of variables declaration//GEN-END:variables
}
