/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.guerra.simplepuntodeventa.vista.reportes;

/**
 *
 * @author Jaasiel
 */
public class PanMenuReportes extends javax.swing.JPanel {

    /**
     * Creates new form PanMenuReportes
     */
    public PanMenuReportes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panCentral = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(241, 246, 249));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        panCentral.setBackground(new java.awt.Color(241, 246, 249));
        panCentral.setLayout(new java.awt.GridLayout(3, 3, 30, 30));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jLabel1.setBackground(new java.awt.Color(0, 102, 51));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-sales-performance-100.png"))); // NOI18N
        jLabel1.setOpaque(true);
        jPanel1.add(jLabel1, java.awt.BorderLayout.LINE_START);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("<html><b style=\"font-size: 14px;\">VENTAS</b>\n<p>Permite ver las ventas realizadas en un rango de fecha especificado.</p>");
        jPanel1.add(jLabel2, java.awt.BorderLayout.CENTER);

        panCentral.add(jPanel1);

        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel8.setLayout(new java.awt.BorderLayout());

        jLabel3.setBackground(new java.awt.Color(0, 102, 102));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-total-sales-100.png"))); // NOI18N
        jLabel3.setOpaque(true);
        jPanel8.add(jLabel3, java.awt.BorderLayout.LINE_START);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("<html><b style=\"font-size: 14px;\">GANANCIAS</b>\n<p>Ver las ganancias obtenidas de las ventas realizadas.</p>");
        jPanel8.add(jLabel4, java.awt.BorderLayout.CENTER);

        panCentral.add(jPanel8);

        jPanel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel9.setLayout(new java.awt.BorderLayout());

        jLabel5.setBackground(new java.awt.Color(0, 51, 102));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-show-property-100.png"))); // NOI18N
        jLabel5.setOpaque(true);
        jPanel9.add(jLabel5, java.awt.BorderLayout.LINE_START);

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("<html><b style=\"font-size: 14px;\">ARTÍCULOS</b>\n<p>Listar todos los artículos registrados en el sistema.</p>");
        jPanel9.add(jLabel6, java.awt.BorderLayout.CENTER);

        panCentral.add(jPanel9);

        jPanel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel10.setLayout(new java.awt.BorderLayout());

        jLabel7.setBackground(new java.awt.Color(102, 0, 0));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-descending-sorting-100.png"))); // NOI18N
        jLabel7.setOpaque(true);
        jPanel10.add(jLabel7, java.awt.BorderLayout.LINE_START);

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel8.setText("<html><b style=\"font-size: 14px;\">BAJOS</b>\n<p>Ver los artículos que están bajos en inventario.</p>");
        jPanel10.add(jLabel8, java.awt.BorderLayout.CENTER);

        panCentral.add(jPanel10);

        jPanel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel11.setLayout(new java.awt.BorderLayout());

        jLabel9.setBackground(new java.awt.Color(102, 51, 0));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-profile-100.png"))); // NOI18N
        jLabel9.setOpaque(true);
        jPanel11.add(jLabel9, java.awt.BorderLayout.LINE_START);

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel10.setText("<html><b style=\"font-size: 14px;\">CRÉDITOS</b>\n<p>Muestra los Clientes que tienen créditos pendientes y su respectivo saldo.</p>");
        jPanel11.add(jLabel10, java.awt.BorderLayout.CENTER);

        panCentral.add(jPanel11);

        jPanel12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel12.setLayout(new java.awt.BorderLayout());

        jLabel11.setBackground(new java.awt.Color(51, 102, 0));
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-shopping-cart-100.png"))); // NOI18N
        jLabel11.setOpaque(true);
        jPanel12.add(jLabel11, java.awt.BorderLayout.LINE_START);

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel12.setText("<html><b style=\"font-size: 14px;\">COMPRAS</b>\n<p>Ver las compras realizadas en un rango de fecha indicado.</p>");
        jPanel12.add(jLabel12, java.awt.BorderLayout.CENTER);

        panCentral.add(jPanel12);

        jPanel13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel13.setLayout(new java.awt.BorderLayout());

        jLabel13.setBackground(new java.awt.Color(102, 0, 102));
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-circled-user-100.png"))); // NOI18N
        jLabel13.setOpaque(true);
        jPanel13.add(jLabel13, java.awt.BorderLayout.LINE_START);

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel14.setText("<html><b style=\"font-size: 14px;\">CUENTAS</b>\n<p>Ver estado de cuenta de un Cliente en específico.</p>");
        jPanel13.add(jLabel14, java.awt.BorderLayout.CENTER);

        panCentral.add(jPanel13);

        jPanel14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel14.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel14.setLayout(new java.awt.BorderLayout());

        jLabel15.setBackground(new java.awt.Color(204, 153, 0));
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-warehouse-100.png"))); // NOI18N
        jLabel15.setOpaque(true);
        jPanel14.add(jLabel15, java.awt.BorderLayout.LINE_START);

        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel16.setText("<html><b style=\"font-size: 14px;\">INVENTARIO</b> <p>Ver todo el inventario de artículos activos.</p>");
        jPanel14.add(jLabel16, java.awt.BorderLayout.CENTER);

        panCentral.add(jPanel14);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panCentral, javax.swing.GroupLayout.DEFAULT_SIZE, 839, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panCentral, javax.swing.GroupLayout.DEFAULT_SIZE, 530, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    public javax.swing.JPanel panCentral;
    // End of variables declaration//GEN-END:variables
}
