/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.guerra.simplepuntodeventa.vista.ventas;

import com.guerra.simplepuntodeventa.recursos.componentes.extensiones.PlaceHolderSupport;

/**
 *
 * @author Jaasiel
 */
public class IfrmVentas extends javax.swing.JInternalFrame {

    /**
     * Creates new form ifrmVentas
     */
    public IfrmVentas() {
        initComponents();
        PlaceHolderSupport.setPlaceHolder("Escriba el código del artículo y presione ENTER", txtCodigo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        spnCantidad = new javax.swing.JSpinner();
        btnAceptar = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        btnBuscarArticulo = new javax.swing.JButton();
        jPanel12 = new javax.swing.JPanel();
        tbdDetalle = new javax.swing.JTabbedPane();
        jPanel13 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        lblCantidadArticulos = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        btnQuitarArticulo = new javax.swing.JButton();
        btnDisminuirCantidad = new javax.swing.JButton();
        btnAumentarCantidad = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        btnEliminarVenta = new javax.swing.JButton();
        btnPendiente = new javax.swing.JButton();
        btnVentasRealizadas = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        btnCobrar = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        ftdTotal = new javax.swing.JFormattedTextField();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("VENTAS");
        setMinimumSize(new java.awt.Dimension(960, 540));
        setPreferredSize(new java.awt.Dimension(960, 540));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setMinimumSize(new java.awt.Dimension(0, 0));
        jPanel5.setLayout(new java.awt.BorderLayout());

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.LINE_AXIS));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-barcode-32.png"))); // NOI18N
        jLabel1.setText("Código de artículo");
        jPanel6.add(jLabel1);

        txtCodigo.setBackground(new java.awt.Color(255, 255, 153));
        txtCodigo.setMinimumSize(new java.awt.Dimension(400, 35));
        txtCodigo.setPreferredSize(new java.awt.Dimension(400, 35));
        jPanel6.add(txtCodigo);

        jLabel4.setText("X");
        jPanel6.add(jLabel4);

        spnCantidad.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        spnCantidad.setMinimumSize(new java.awt.Dimension(75, 35));
        spnCantidad.setPreferredSize(new java.awt.Dimension(75, 35));
        jPanel6.add(spnCantidad);

        btnAceptar.setText("ACEPTAR");
        btnAceptar.setPreferredSize(new java.awt.Dimension(84, 35));
        jPanel6.add(btnAceptar);

        jPanel4.add(jPanel6);

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));
        jPanel11.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        btnBuscarArticulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-package-search-28.png"))); // NOI18N
        btnBuscarArticulo.setText("BUSCAR");
        btnBuscarArticulo.setToolTipText("Realizar una búsqueda de artículo por descripción");
        btnBuscarArticulo.setFocusPainted(false);
        btnBuscarArticulo.setPreferredSize(new java.awt.Dimension(121, 35));
        jPanel11.add(btnBuscarArticulo);

        jPanel4.add(jPanel11);

        jPanel5.add(jPanel4, java.awt.BorderLayout.PAGE_START);

        jPanel12.setLayout(new java.awt.BorderLayout());
        jPanel12.add(tbdDetalle, java.awt.BorderLayout.CENTER);

        jPanel13.setLayout(new javax.swing.BoxLayout(jPanel13, javax.swing.BoxLayout.LINE_AXIS));

        jPanel14.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        lblCantidadArticulos.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblCantidadArticulos.setForeground(new java.awt.Color(183, 28, 28));
        lblCantidadArticulos.setText("0");
        jPanel14.add(lblCantidadArticulos);

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(13, 71, 161));
        jLabel6.setText("ARTÍCULO(S) EN LA VENTA");
        jPanel14.add(jLabel6);

        jPanel13.add(jPanel14);

        jPanel10.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        btnQuitarArticulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-delete-bin-16.png"))); // NOI18N
        btnQuitarArticulo.setText("QUITAR ARTÍCULO");
        btnQuitarArticulo.setToolTipText("Quitar el artículo de la fila seleccionada");
        btnQuitarArticulo.setFocusPainted(false);
        jPanel10.add(btnQuitarArticulo);

        btnDisminuirCantidad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-minus-16.png"))); // NOI18N
        btnDisminuirCantidad.setText("DISMINUIR CANTIDAD");
        btnDisminuirCantidad.setToolTipText("Disminuir en 1 (uno) la cantidad del artículo de la fila seleccionada");
        btnDisminuirCantidad.setFocusPainted(false);
        jPanel10.add(btnDisminuirCantidad);

        btnAumentarCantidad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-add-16.png"))); // NOI18N
        btnAumentarCantidad.setText("AUMENTAR CANTIDAD");
        btnAumentarCantidad.setToolTipText("Aumentar en 1 (uno) la cantidad del artículo de la fila seleccionada");
        btnAumentarCantidad.setFocusPainted(false);
        jPanel10.add(btnAumentarCantidad);

        jPanel13.add(jPanel10);

        jPanel12.add(jPanel13, java.awt.BorderLayout.PAGE_END);

        jPanel5.add(jPanel12, java.awt.BorderLayout.CENTER);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.X_AXIS));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        btnEliminarVenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-delete-32.png"))); // NOI18N
        btnEliminarVenta.setText("ELIMINAR VENTA");
        btnEliminarVenta.setToolTipText("Eliminar la venta actual");
        btnEliminarVenta.setFocusPainted(false);
        btnEliminarVenta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEliminarVenta.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel7.add(btnEliminarVenta);

        btnPendiente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-delivery-time-32.png"))); // NOI18N
        btnPendiente.setText("PONER PENDIENTE");
        btnPendiente.setToolTipText("Poner pendiente esta venta");
        btnPendiente.setFocusPainted(false);
        btnPendiente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPendiente.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel7.add(btnPendiente);

        btnVentasRealizadas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-sales-performance-32.png"))); // NOI18N
        btnVentasRealizadas.setText("VENTAS REALIZADAS");
        btnVentasRealizadas.setToolTipText("Ver las ventas realizadas del día o una fecha específica");
        btnVentasRealizadas.setFocusPainted(false);
        btnVentasRealizadas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnVentasRealizadas.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel7.add(btnVentasRealizadas);

        jPanel3.add(jPanel7);

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        btnCobrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-cash-32.png"))); // NOI18N
        btnCobrar.setText("COBRAR VENTA");
        btnCobrar.setFocusPainted(false);
        btnCobrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCobrar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel8.add(btnCobrar);

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("TOTAL A COBRAR");

        ftdTotal.setEditable(false);
        ftdTotal.setForeground(new java.awt.Color(27, 94, 32));
        ftdTotal.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getCurrencyInstance())));
        ftdTotal.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        ftdTotal.setToolTipText("Total de la venta");
        ftdTotal.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        ftdTotal.setMinimumSize(new java.awt.Dimension(200, 35));
        ftdTotal.setPreferredSize(new java.awt.Dimension(200, 35));
        ftdTotal.setValue(0);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                    .addComponent(ftdTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ftdTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel8.add(jPanel9);

        jPanel3.add(jPanel8);

        jPanel5.add(jPanel3, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(jPanel5, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnAceptar;
    public javax.swing.JButton btnAumentarCantidad;
    public javax.swing.JButton btnBuscarArticulo;
    public javax.swing.JButton btnCobrar;
    public javax.swing.JButton btnDisminuirCantidad;
    public javax.swing.JButton btnEliminarVenta;
    public javax.swing.JButton btnPendiente;
    public javax.swing.JButton btnQuitarArticulo;
    public javax.swing.JButton btnVentasRealizadas;
    public javax.swing.JFormattedTextField ftdTotal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    public javax.swing.JLabel lblCantidadArticulos;
    public javax.swing.JSpinner spnCantidad;
    public javax.swing.JTabbedPane tbdDetalle;
    public javax.swing.JTextField txtCodigo;
    // End of variables declaration//GEN-END:variables
}
