/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.guerra.simplepuntodeventa.vista.compras;

import javax.swing.JPanel;

/**
 *
 * @author Jaasiel
 */
public class PanMenuCompra extends javax.swing.JPanel {

    public static JPanel PANEL_CAMBIANTE;

    /**
     * Creates new form PanMenuCompra
     */
    public PanMenuCompra() {
        initComponents();
        PanMenuCompra.PANEL_CAMBIANTE = panCentral;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panMenu = new javax.swing.JPanel();
        btnConsultarCompras = new javax.swing.JButton();
        btnNuevaCompra = new javax.swing.JButton();
        panCentral = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(241, 246, 249));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel1.setLayout(new java.awt.BorderLayout());

        panMenu.setBackground(new java.awt.Color(241, 246, 249));
        panMenu.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        btnConsultarCompras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-shopping-cart-16.png"))); // NOI18N
        btnConsultarCompras.setText("Consultar compras");
        btnConsultarCompras.setFocusPainted(false);
        panMenu.add(btnConsultarCompras);

        btnNuevaCompra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-add-shopping-cart-16.png"))); // NOI18N
        btnNuevaCompra.setText("Nueva compra");
        btnNuevaCompra.setFocusPainted(false);
        panMenu.add(btnNuevaCompra);

        jPanel1.add(panMenu, java.awt.BorderLayout.PAGE_START);

        panCentral.setLayout(new java.awt.BorderLayout());
        jPanel1.add(panCentral, java.awt.BorderLayout.CENTER);

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnConsultarCompras;
    public javax.swing.JButton btnNuevaCompra;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JPanel panCentral;
    private javax.swing.JPanel panMenu;
    // End of variables declaration//GEN-END:variables
}
